services:
  faster-whisper:
    image: ghcr.io/speaches-ai/speaches:0.8.3-cpu
    environment:
      WHISPER__INFERENCE_DEVICE: cpu
      WHISPER__COMPUTE_TYPE: int8

  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.9.0
    environment:
      DEVICE_TYPE: cpu
      USE_GPU: "false"
